#! /bin/sh
# /etc/init.d/shutdown

### BEGIN INIT INFO
# Provides:          shutdown
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Shutdown and servo controller script for MotorPiTX board
# Description:       This will start the Python script to switch on the Ready LED, and listen for the shutdown command from the ATTiny and start the servos
### END INIT INFO


 case "$1" in
  start)
    sudo /etc/./servod
    sudo python /etc/shutdown.py
    ;;
  stop)
    ;;
  *)
    sleep 2s
    killall python
    exit 1
    ;;

esac
exit 0


